### PR TITLE
port pdf_stream data storage to Vec

### LINKED ISSUE #170: Undefined behaviour in pdf_parse_obj / skip_white
Reproducing test case: [1702.06898](https://arxiv.org/e-print/1702.06898), 1702.08278

Note: This issue is present in the original C code.

<details><summary>valgrind tectonic @ master</summary>

```console
$ ~/_/_/tectonic on master ⨯ valgrind --track-origins=yes target/debug/tectonic /tmp/repro/pf_paper.tex
==137415== Memcheck, a memory error detector
==137415== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==137415== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==137415== Command: target/debug/tectonic /tmp/repro/pf_paper.tex
==137415== 
note: this is a BETA release; ask questions and report bugs at https://tectonic.newton.cx/
Running TeX ...
==137415== Conditional jump or move depends on uninitialised value(s)
==137415==    at 0x4C27CA: skip_white (dpx-pdfparse.c:111)
==137415==    by 0x4C4B4C: parse_pdf_object (dpx-pdfparse.c:946)
==137415==    by 0x4C0758: pdf_get_object (dpx-pdfobj.c:3007)
==137415==    by 0x4C08A7: pdf_deref_obj (dpx-pdfobj.c:3056)
==137415==    by 0x4C1DA6: pdf_open (dpx-pdfobj.c:3609)
==137415==    by 0x5FDE4D: pdf_get_rect (xetex-pic.c:109)
==137415==    by 0x5FE434: find_pic_file (xetex-pic.c:236)
==137415==    by 0x5FEAC1: load_picture (xetex-pic.c:368)
==137415==    by 0x5470EC: do_extension (xetex-xetex0.c:16282)
==137415==    by 0x54947D: main_control (xetex-xetex0.c:17319)
==137415==    by 0x4F7D3B: tt_run_engine (xetex-ini.c:4369)
==137415==    by 0x49FEDB: tex_simple_main (core-bridge.c:66)
==137415==  Uninitialised value was created by a heap allocation
==137415==    at 0x48386AF: malloc (vg_replace_malloc.c:308)
==137415==    by 0x483ADE7: realloc (vg_replace_malloc.c:836)
==137415==    by 0x4A50F2: renew (dpx-mem.c:42)
==137415==    by 0x4BDC95: pdf_add_stream (dpx-pdfobj.c:2018)
==137415==    by 0x4BDE6C: pdf_add_stream_flate (dpx-pdfobj.c:2061)
==137415==    by 0x4BEF35: pdf_concat_stream (dpx-pdfobj.c:2403)
==137415==    by 0x4BF037: pdf_stream_uncompress (dpx-pdfobj.c:2424)
==137415==    by 0x4C0177: read_objstm (dpx-pdfobj.c:2895)
==137415==    by 0x4C0641: pdf_get_object (dpx-pdfobj.c:2994)
==137415==    by 0x4C08A7: pdf_deref_obj (dpx-pdfobj.c:3056)
==137415==    by 0x4C1DA6: pdf_open (dpx-pdfobj.c:3609)
==137415==    by 0x5FDE4D: pdf_get_rect (xetex-pic.c:109)
==137415== 
==137415== Conditional jump or move depends on uninitialised value(s)
==137415==    at 0x4C27D8: skip_white (dpx-pdfparse.c:111)
==137415==    by 0x4C4B4C: parse_pdf_object (dpx-pdfparse.c:946)
==137415==    by 0x4C0758: pdf_get_object (dpx-pdfobj.c:3007)
==137415==    by 0x4C08A7: pdf_deref_obj (dpx-pdfobj.c:3056)
==137415==    by 0x4C1DA6: pdf_open (dpx-pdfobj.c:3609)
==137415==    by 0x5FDE4D: pdf_get_rect (xetex-pic.c:109)
==137415==    by 0x5FE434: find_pic_file (xetex-pic.c:236)
==137415==    by 0x5FEAC1: load_picture (xetex-pic.c:368)
==137415==    by 0x5470EC: do_extension (xetex-xetex0.c:16282)
==137415==    by 0x54947D: main_control (xetex-xetex0.c:17319)
==137415==    by 0x4F7D3B: tt_run_engine (xetex-ini.c:4369)
==137415==    by 0x49FEDB: tex_simple_main (core-bridge.c:66)
==137415==  Uninitialised value was created by a heap allocation
==137415==    at 0x48386AF: malloc (vg_replace_malloc.c:308)
==137415==    by 0x483ADE7: realloc (vg_replace_malloc.c:836)
==137415==    by 0x4A50F2: renew (dpx-mem.c:42)
==137415==    by 0x4BDC95: pdf_add_stream (dpx-pdfobj.c:2018)
==137415==    by 0x4BDE6C: pdf_add_stream_flate (dpx-pdfobj.c:2061)
==137415==    by 0x4BEF35: pdf_concat_stream (dpx-pdfobj.c:2403)
==137415==    by 0x4BF037: pdf_stream_uncompress (dpx-pdfobj.c:2424)
==137415==    by 0x4C0177: read_objstm (dpx-pdfobj.c:2895)
==137415==    by 0x4C0641: pdf_get_object (dpx-pdfobj.c:2994)
==137415==    by 0x4C08A7: pdf_deref_obj (dpx-pdfobj.c:3056)
==137415==    by 0x4C1DA6: pdf_open (dpx-pdfobj.c:3609)
==137415==    by 0x5FDE4D: pdf_get_rect (xetex-pic.c:109)
==137415== 
==137415== Conditional jump or move depends on uninitialised value(s)
==137415==    at 0x4C27E6: skip_white (dpx-pdfparse.c:111)
==137415==    by 0x4C4B4C: parse_pdf_object (dpx-pdfparse.c:946)
==137415==    by 0x4C0758: pdf_get_object (dpx-pdfobj.c:3007)
==137415==    by 0x4C08A7: pdf_deref_obj (dpx-pdfobj.c:3056)
==137415==    by 0x4C1DA6: pdf_open (dpx-pdfobj.c:3609)
==137415==    by 0x5FDE4D: pdf_get_rect (xetex-pic.c:109)
==137415==    by 0x5FE434: find_pic_file (xetex-pic.c:236)
==137415==    by 0x5FEAC1: load_picture (xetex-pic.c:368)
==137415==    by 0x5470EC: do_extension (xetex-xetex0.c:16282)
==137415==    by 0x54947D: main_control (xetex-xetex0.c:17319)
==137415==    by 0x4F7D3B: tt_run_engine (xetex-ini.c:4369)
==137415==    by 0x49FEDB: tex_simple_main (core-bridge.c:66)
==137415==  Uninitialised value was created by a heap allocation
==137415==    at 0x48386AF: malloc (vg_replace_malloc.c:308)
==137415==    by 0x483ADE7: realloc (vg_replace_malloc.c:836)
==137415==    by 0x4A50F2: renew (dpx-mem.c:42)
==137415==    by 0x4BDC95: pdf_add_stream (dpx-pdfobj.c:2018)
==137415==    by 0x4BDE6C: pdf_add_stream_flate (dpx-pdfobj.c:2061)
==137415==    by 0x4BEF35: pdf_concat_stream (dpx-pdfobj.c:2403)
==137415==    by 0x4BF037: pdf_stream_uncompress (dpx-pdfobj.c:2424)
==137415==    by 0x4C0177: read_objstm (dpx-pdfobj.c:2895)
==137415==    by 0x4C0641: pdf_get_object (dpx-pdfobj.c:2994)
==137415==    by 0x4C08A7: pdf_deref_obj (dpx-pdfobj.c:3056)
==137415==    by 0x4C1DA6: pdf_open (dpx-pdfobj.c:3609)
==137415==    by 0x5FDE4D: pdf_get_rect (xetex-pic.c:109)
==137415== 
==137415== Conditional jump or move depends on uninitialised value(s)
==137415==    at 0x4C27F4: skip_white (dpx-pdfparse.c:111)
==137415==    by 0x4C4B4C: parse_pdf_object (dpx-pdfparse.c:946)
==137415==    by 0x4C0758: pdf_get_object (dpx-pdfobj.c:3007)
==137415==    by 0x4C08A7: pdf_deref_obj (dpx-pdfobj.c:3056)
==137415==    by 0x4C1DA6: pdf_open (dpx-pdfobj.c:3609)
==137415==    by 0x5FDE4D: pdf_get_rect (xetex-pic.c:109)
==137415==    by 0x5FE434: find_pic_file (xetex-pic.c:236)
==137415==    by 0x5FEAC1: load_picture (xetex-pic.c:368)
==137415==    by 0x5470EC: do_extension (xetex-xetex0.c:16282)
==137415==    by 0x54947D: main_control (xetex-xetex0.c:17319)
==137415==    by 0x4F7D3B: tt_run_engine (xetex-ini.c:4369)
==137415==    by 0x49FEDB: tex_simple_main (core-bridge.c:66)
==137415==  Uninitialised value was created by a heap allocation
==137415==    at 0x48386AF: malloc (vg_replace_malloc.c:308)
==137415==    by 0x483ADE7: realloc (vg_replace_malloc.c:836)
==137415==    by 0x4A50F2: renew (dpx-mem.c:42)
==137415==    by 0x4BDC95: pdf_add_stream (dpx-pdfobj.c:2018)
==137415==    by 0x4BDE6C: pdf_add_stream_flate (dpx-pdfobj.c:2061)
==137415==    by 0x4BEF35: pdf_concat_stream (dpx-pdfobj.c:2403)
==137415==    by 0x4BF037: pdf_stream_uncompress (dpx-pdfobj.c:2424)
==137415==    by 0x4C0177: read_objstm (dpx-pdfobj.c:2895)
==137415==    by 0x4C0641: pdf_get_object (dpx-pdfobj.c:2994)
==137415==    by 0x4C08A7: pdf_deref_obj (dpx-pdfobj.c:3056)
==137415==    by 0x4C1DA6: pdf_open (dpx-pdfobj.c:3609)
==137415==    by 0x5FDE4D: pdf_get_rect (xetex-pic.c:109)
==137415== 
==137415== Conditional jump or move depends on uninitialised value(s)
==137415==    at 0x4C2802: skip_white (dpx-pdfparse.c:111)
==137415==    by 0x4C4B4C: parse_pdf_object (dpx-pdfparse.c:946)
==137415==    by 0x4C0758: pdf_get_object (dpx-pdfobj.c:3007)
==137415==    by 0x4C08A7: pdf_deref_obj (dpx-pdfobj.c:3056)
==137415==    by 0x4C1DA6: pdf_open (dpx-pdfobj.c:3609)
==137415==    by 0x5FDE4D: pdf_get_rect (xetex-pic.c:109)
==137415==    by 0x5FE434: find_pic_file (xetex-pic.c:236)
==137415==    by 0x5FEAC1: load_picture (xetex-pic.c:368)
==137415==    by 0x5470EC: do_extension (xetex-xetex0.c:16282)
==137415==    by 0x54947D: main_control (xetex-xetex0.c:17319)
==137415==    by 0x4F7D3B: tt_run_engine (xetex-ini.c:4369)
==137415==    by 0x49FEDB: tex_simple_main (core-bridge.c:66)
==137415==  Uninitialised value was created by a heap allocation
==137415==    at 0x48386AF: malloc (vg_replace_malloc.c:308)
==137415==    by 0x483ADE7: realloc (vg_replace_malloc.c:836)
==137415==    by 0x4A50F2: renew (dpx-mem.c:42)
==137415==    by 0x4BDC95: pdf_add_stream (dpx-pdfobj.c:2018)
==137415==    by 0x4BDE6C: pdf_add_stream_flate (dpx-pdfobj.c:2061)
==137415==    by 0x4BEF35: pdf_concat_stream (dpx-pdfobj.c:2403)
==137415==    by 0x4BF037: pdf_stream_uncompress (dpx-pdfobj.c:2424)
==137415==    by 0x4C0177: read_objstm (dpx-pdfobj.c:2895)
==137415==    by 0x4C0641: pdf_get_object (dpx-pdfobj.c:2994)
==137415==    by 0x4C08A7: pdf_deref_obj (dpx-pdfobj.c:3056)
==137415==    by 0x4C1DA6: pdf_open (dpx-pdfobj.c:3609)
==137415==    by 0x5FDE4D: pdf_get_rect (xetex-pic.c:109)
==137415== 
==137415== Conditional jump or move depends on uninitialised value(s)
==137415==    at 0x4C2814: skip_white (dpx-pdfparse.c:111)
==137415==    by 0x4C4B4C: parse_pdf_object (dpx-pdfparse.c:946)
==137415==    by 0x4C0758: pdf_get_object (dpx-pdfobj.c:3007)
==137415==    by 0x4C08A7: pdf_deref_obj (dpx-pdfobj.c:3056)
==137415==    by 0x4C1DA6: pdf_open (dpx-pdfobj.c:3609)
==137415==    by 0x5FDE4D: pdf_get_rect (xetex-pic.c:109)
==137415==    by 0x5FE434: find_pic_file (xetex-pic.c:236)
==137415==    by 0x5FEAC1: load_picture (xetex-pic.c:368)
==137415==    by 0x5470EC: do_extension (xetex-xetex0.c:16282)
==137415==    by 0x54947D: main_control (xetex-xetex0.c:17319)
==137415==    by 0x4F7D3B: tt_run_engine (xetex-ini.c:4369)
==137415==    by 0x49FEDB: tex_simple_main (core-bridge.c:66)
==137415==  Uninitialised value was created by a heap allocation
==137415==    at 0x48386AF: malloc (vg_replace_malloc.c:308)
==137415==    by 0x483ADE7: realloc (vg_replace_malloc.c:836)
==137415==    by 0x4A50F2: renew (dpx-mem.c:42)
==137415==    by 0x4BDC95: pdf_add_stream (dpx-pdfobj.c:2018)
==137415==    by 0x4BDE6C: pdf_add_stream_flate (dpx-pdfobj.c:2061)
==137415==    by 0x4BEF35: pdf_concat_stream (dpx-pdfobj.c:2403)
==137415==    by 0x4BF037: pdf_stream_uncompress (dpx-pdfobj.c:2424)
==137415==    by 0x4C0177: read_objstm (dpx-pdfobj.c:2895)
==137415==    by 0x4C0641: pdf_get_object (dpx-pdfobj.c:2994)
==137415==    by 0x4C08A7: pdf_deref_obj (dpx-pdfobj.c:3056)
==137415==    by 0x4C1DA6: pdf_open (dpx-pdfobj.c:3609)
==137415==    by 0x5FDE4D: pdf_get_rect (xetex-pic.c:109)
==137415== 
==137415== Conditional jump or move depends on uninitialised value(s)
==137415==    at 0x4C2826: skip_white (dpx-pdfparse.c:111)
==137415==    by 0x4C4B4C: parse_pdf_object (dpx-pdfparse.c:946)
==137415==    by 0x4C0758: pdf_get_object (dpx-pdfobj.c:3007)
==137415==    by 0x4C08A7: pdf_deref_obj (dpx-pdfobj.c:3056)
==137415==    by 0x4C1DA6: pdf_open (dpx-pdfobj.c:3609)
==137415==    by 0x5FDE4D: pdf_get_rect (xetex-pic.c:109)
==137415==    by 0x5FE434: find_pic_file (xetex-pic.c:236)
==137415==    by 0x5FEAC1: load_picture (xetex-pic.c:368)
==137415==    by 0x5470EC: do_extension (xetex-xetex0.c:16282)
==137415==    by 0x54947D: main_control (xetex-xetex0.c:17319)
==137415==    by 0x4F7D3B: tt_run_engine (xetex-ini.c:4369)
==137415==    by 0x49FEDB: tex_simple_main (core-bridge.c:66)
==137415==  Uninitialised value was created by a heap allocation
==137415==    at 0x48386AF: malloc (vg_replace_malloc.c:308)
==137415==    by 0x483ADE7: realloc (vg_replace_malloc.c:836)
==137415==    by 0x4A50F2: renew (dpx-mem.c:42)
==137415==    by 0x4BDC95: pdf_add_stream (dpx-pdfobj.c:2018)
==137415==    by 0x4BDE6C: pdf_add_stream_flate (dpx-pdfobj.c:2061)
==137415==    by 0x4BEF35: pdf_concat_stream (dpx-pdfobj.c:2403)
==137415==    by 0x4BF037: pdf_stream_uncompress (dpx-pdfobj.c:2424)
==137415==    by 0x4C0177: read_objstm (dpx-pdfobj.c:2895)
==137415==    by 0x4C0641: pdf_get_object (dpx-pdfobj.c:2994)
==137415==    by 0x4C08A7: pdf_deref_obj (dpx-pdfobj.c:3056)
==137415==    by 0x4C1DA6: pdf_open (dpx-pdfobj.c:3609)
==137415==    by 0x5FDE4D: pdf_get_rect (xetex-pic.c:109)
==137415== 
==137415== Conditional jump or move depends on uninitialised value(s)
==137415==    at 0x483EEC5: bcmp (vg_replace_strmem.c:1113)
==137415==    by 0x4C4B8A: parse_pdf_object (dpx-pdfparse.c:949)
==137415==    by 0x4C0758: pdf_get_object (dpx-pdfobj.c:3007)
==137415==    by 0x4C08A7: pdf_deref_obj (dpx-pdfobj.c:3056)
==137415==    by 0x4C1DA6: pdf_open (dpx-pdfobj.c:3609)
==137415==    by 0x5FDE4D: pdf_get_rect (xetex-pic.c:109)
==137415==    by 0x5FE434: find_pic_file (xetex-pic.c:236)
==137415==    by 0x5FEAC1: load_picture (xetex-pic.c:368)
==137415==    by 0x5470EC: do_extension (xetex-xetex0.c:16282)
==137415==    by 0x54947D: main_control (xetex-xetex0.c:17319)
==137415==    by 0x4F7D3B: tt_run_engine (xetex-ini.c:4369)
==137415==    by 0x49FEDB: tex_simple_main (core-bridge.c:66)
==137415==  Uninitialised value was created by a heap allocation
==137415==    at 0x48386AF: malloc (vg_replace_malloc.c:308)
==137415==    by 0x483ADE7: realloc (vg_replace_malloc.c:836)
==137415==    by 0x4A50F2: renew (dpx-mem.c:42)
==137415==    by 0x4BDC95: pdf_add_stream (dpx-pdfobj.c:2018)
==137415==    by 0x4BDE6C: pdf_add_stream_flate (dpx-pdfobj.c:2061)
==137415==    by 0x4BEF35: pdf_concat_stream (dpx-pdfobj.c:2403)
==137415==    by 0x4BF037: pdf_stream_uncompress (dpx-pdfobj.c:2424)
==137415==    by 0x4C0177: read_objstm (dpx-pdfobj.c:2895)
==137415==    by 0x4C0641: pdf_get_object (dpx-pdfobj.c:2994)
==137415==    by 0x4C08A7: pdf_deref_obj (dpx-pdfobj.c:3056)
==137415==    by 0x4C1DA6: pdf_open (dpx-pdfobj.c:3609)
==137415==    by 0x5FDE4D: pdf_get_rect (xetex-pic.c:109)
==137415== 
==137415== Conditional jump or move depends on uninitialised value(s)
==137415==    at 0x4C4B8D: parse_pdf_object (dpx-pdfparse.c:948)
==137415==    by 0x4C0758: pdf_get_object (dpx-pdfobj.c:3007)
==137415==    by 0x4C08A7: pdf_deref_obj (dpx-pdfobj.c:3056)
==137415==    by 0x4C1DA6: pdf_open (dpx-pdfobj.c:3609)
==137415==    by 0x5FDE4D: pdf_get_rect (xetex-pic.c:109)
==137415==    by 0x5FE434: find_pic_file (xetex-pic.c:236)
==137415==    by 0x5FEAC1: load_picture (xetex-pic.c:368)
==137415==    by 0x5470EC: do_extension (xetex-xetex0.c:16282)
==137415==    by 0x54947D: main_control (xetex-xetex0.c:17319)
==137415==    by 0x4F7D3B: tt_run_engine (xetex-ini.c:4369)
==137415==    by 0x49FEDB: tex_simple_main (core-bridge.c:66)
==137415==    by 0x40A766: tectonic::engines::tex::TexEngine::process (tex.rs:144)
==137415==  Uninitialised value was created by a heap allocation
==137415==    at 0x48386AF: malloc (vg_replace_malloc.c:308)
==137415==    by 0x483ADE7: realloc (vg_replace_malloc.c:836)
==137415==    by 0x4A50F2: renew (dpx-mem.c:42)
==137415==    by 0x4BDC95: pdf_add_stream (dpx-pdfobj.c:2018)
==137415==    by 0x4BDE6C: pdf_add_stream_flate (dpx-pdfobj.c:2061)
==137415==    by 0x4BEF35: pdf_concat_stream (dpx-pdfobj.c:2403)
==137415==    by 0x4BF037: pdf_stream_uncompress (dpx-pdfobj.c:2424)
==137415==    by 0x4C0177: read_objstm (dpx-pdfobj.c:2895)
==137415==    by 0x4C0641: pdf_get_object (dpx-pdfobj.c:2994)
==137415==    by 0x4C08A7: pdf_deref_obj (dpx-pdfobj.c:3056)
==137415==    by 0x4C1DA6: pdf_open (dpx-pdfobj.c:3609)
==137415==    by 0x5FDE4D: pdf_get_rect (xetex-pic.c:109)
==137415== 
==137415== Conditional jump or move depends on uninitialised value(s)
==137415==    at 0x4C2788: skip_white (dpx-pdfparse.c:112)
==137415==    by 0x4C4B4C: parse_pdf_object (dpx-pdfparse.c:946)
==137415==    by 0x4C0758: pdf_get_object (dpx-pdfobj.c:3007)
==137415==    by 0x4C08A7: pdf_deref_obj (dpx-pdfobj.c:3056)
==137415==    by 0x4C1DA6: pdf_open (dpx-pdfobj.c:3609)
==137415==    by 0x5FDE4D: pdf_get_rect (xetex-pic.c:109)
==137415==    by 0x5FE434: find_pic_file (xetex-pic.c:236)
==137415==    by 0x5FEAC1: load_picture (xetex-pic.c:368)
==137415==    by 0x5470EC: do_extension (xetex-xetex0.c:16282)
==137415==    by 0x54947D: main_control (xetex-xetex0.c:17319)
==137415==    by 0x4F7D3B: tt_run_engine (xetex-ini.c:4369)
==137415==    by 0x49FEDB: tex_simple_main (core-bridge.c:66)
==137415==  Uninitialised value was created by a heap allocation
==137415==    at 0x48386AF: malloc (vg_replace_malloc.c:308)
==137415==    by 0x483ADE7: realloc (vg_replace_malloc.c:836)
==137415==    by 0x4A50F2: renew (dpx-mem.c:42)
==137415==    by 0x4BDC95: pdf_add_stream (dpx-pdfobj.c:2018)
==137415==    by 0x4BDE6C: pdf_add_stream_flate (dpx-pdfobj.c:2061)
==137415==    by 0x4BEF35: pdf_concat_stream (dpx-pdfobj.c:2403)
==137415==    by 0x4BF037: pdf_stream_uncompress (dpx-pdfobj.c:2424)
==137415==    by 0x4C0177: read_objstm (dpx-pdfobj.c:2895)
==137415==    by 0x4C0641: pdf_get_object (dpx-pdfobj.c:2994)
==137415==    by 0x4C08A7: pdf_deref_obj (dpx-pdfobj.c:3056)
==137415==    by 0x4C1DA6: pdf_open (dpx-pdfobj.c:3609)
==137415==    by 0x5FDE4D: pdf_get_rect (xetex-pic.c:109)
==137415== 
note: warnings were issued by the TeX engine; use --print and/or --keep-logs for details.
Running BibTeX ...
warning: errors were issued by BibTeX, but were ignored; use --print and/or --keep-logs for details.
Rerunning TeX because bibtex was run ...
Rerunning TeX because "pf_paper.aux" changed ...
Running xdvipdfmx ...
==137415== Conditional jump or move depends on uninitialised value(s)
==137415==    at 0x5C3CC6: min4 (dpx-dpxutil.c:52)
==137415==    by 0x4C636A: pdf_ximage_set_form (dpx-pdfximage.c:506)
==137415==    by 0x5CB639: pdf_include_page (dpx-epdf.c:497)
==137415==    by 0x4C5C2D: load_image (dpx-pdfximage.c:282)
==137415==    by 0x4C5EDE: pdf_ximage_findresource (dpx-pdfximage.c:368)
==137415==    by 0x5DE5E8: spc_handler_pdfm_image (dpx-spc_pdfm.c:998)
==137415==    by 0x4CFAF6: spc_exec_special (dpx-specials.c:579)
==137415==    by 0x5C6772: dvi_do_special (dpx-dvi.c:751)
==137415==    by 0x5C85A4: do_xxx (dpx-dvi.c:1443)
==137415==    by 0x5C959A: dvi_do_page (dpx-dvi.c:1869)
==137415==    by 0x4A13BA: do_dvi_pages (dpx-dvipdfmx.c:341)
==137415==    by 0x4A1A6A: dvipdfmx_main (dpx-dvipdfmx.c:516)
==137415==  Uninitialised value was created by a stack allocation
==137415==    at 0x4C6240: pdf_ximage_set_form (dpx-pdfximage.c:488)
==137415== 
==137415== Conditional jump or move depends on uninitialised value(s)
==137415==    at 0x5C3CC6: min4 (dpx-dpxutil.c:52)
==137415==    by 0x4C63A0: pdf_ximage_set_form (dpx-pdfximage.c:507)
==137415==    by 0x5CB639: pdf_include_page (dpx-epdf.c:497)
==137415==    by 0x4C5C2D: load_image (dpx-pdfximage.c:282)
==137415==    by 0x4C5EDE: pdf_ximage_findresource (dpx-pdfximage.c:368)
==137415==    by 0x5DE5E8: spc_handler_pdfm_image (dpx-spc_pdfm.c:998)
==137415==    by 0x4CFAF6: spc_exec_special (dpx-specials.c:579)
==137415==    by 0x5C6772: dvi_do_special (dpx-dvi.c:751)
==137415==    by 0x5C85A4: do_xxx (dpx-dvi.c:1443)
==137415==    by 0x5C959A: dvi_do_page (dpx-dvi.c:1869)
==137415==    by 0x4A13BA: do_dvi_pages (dpx-dvipdfmx.c:341)
==137415==    by 0x4A1A6A: dvipdfmx_main (dpx-dvipdfmx.c:516)
==137415==  Uninitialised value was created by a stack allocation
==137415==    at 0x4C6240: pdf_ximage_set_form (dpx-pdfximage.c:488)
==137415== 
==137415== Conditional jump or move depends on uninitialised value(s)
==137415==    at 0x5C3D31: max4 (dpx-dpxutil.c:63)
==137415==    by 0x4C63D6: pdf_ximage_set_form (dpx-pdfximage.c:508)
==137415==    by 0x5CB639: pdf_include_page (dpx-epdf.c:497)
==137415==    by 0x4C5C2D: load_image (dpx-pdfximage.c:282)
==137415==    by 0x4C5EDE: pdf_ximage_findresource (dpx-pdfximage.c:368)
==137415==    by 0x5DE5E8: spc_handler_pdfm_image (dpx-spc_pdfm.c:998)
==137415==    by 0x4CFAF6: spc_exec_special (dpx-specials.c:579)
==137415==    by 0x5C6772: dvi_do_special (dpx-dvi.c:751)
==137415==    by 0x5C85A4: do_xxx (dpx-dvi.c:1443)
==137415==    by 0x5C959A: dvi_do_page (dpx-dvi.c:1869)
==137415==    by 0x4A13BA: do_dvi_pages (dpx-dvipdfmx.c:341)
==137415==    by 0x4A1A6A: dvipdfmx_main (dpx-dvipdfmx.c:516)
==137415==  Uninitialised value was created by a stack allocation
==137415==    at 0x4C6240: pdf_ximage_set_form (dpx-pdfximage.c:488)
==137415== 
==137415== Conditional jump or move depends on uninitialised value(s)
==137415==    at 0x5C3D47: max4 (dpx-dpxutil.c:64)
==137415==    by 0x4C63D6: pdf_ximage_set_form (dpx-pdfximage.c:508)
==137415==    by 0x5CB639: pdf_include_page (dpx-epdf.c:497)
==137415==    by 0x4C5C2D: load_image (dpx-pdfximage.c:282)
==137415==    by 0x4C5EDE: pdf_ximage_findresource (dpx-pdfximage.c:368)
==137415==    by 0x5DE5E8: spc_handler_pdfm_image (dpx-spc_pdfm.c:998)
==137415==    by 0x4CFAF6: spc_exec_special (dpx-specials.c:579)
==137415==    by 0x5C6772: dvi_do_special (dpx-dvi.c:751)
==137415==    by 0x5C85A4: do_xxx (dpx-dvi.c:1443)
==137415==    by 0x5C959A: dvi_do_page (dpx-dvi.c:1869)
==137415==    by 0x4A13BA: do_dvi_pages (dpx-dvipdfmx.c:341)
==137415==    by 0x4A1A6A: dvipdfmx_main (dpx-dvipdfmx.c:516)
==137415==  Uninitialised value was created by a stack allocation
==137415==    at 0x4C6240: pdf_ximage_set_form (dpx-pdfximage.c:488)
==137415== 
==137415== Conditional jump or move depends on uninitialised value(s)
==137415==    at 0x5C3D5D: max4 (dpx-dpxutil.c:65)
==137415==    by 0x4C63D6: pdf_ximage_set_form (dpx-pdfximage.c:508)
==137415==    by 0x5CB639: pdf_include_page (dpx-epdf.c:497)
==137415==    by 0x4C5C2D: load_image (dpx-pdfximage.c:282)
==137415==    by 0x4C5EDE: pdf_ximage_findresource (dpx-pdfximage.c:368)
==137415==    by 0x5DE5E8: spc_handler_pdfm_image (dpx-spc_pdfm.c:998)
==137415==    by 0x4CFAF6: spc_exec_special (dpx-specials.c:579)
==137415==    by 0x5C6772: dvi_do_special (dpx-dvi.c:751)
==137415==    by 0x5C85A4: do_xxx (dpx-dvi.c:1443)
==137415==    by 0x5C959A: dvi_do_page (dpx-dvi.c:1869)
==137415==    by 0x4A13BA: do_dvi_pages (dpx-dvipdfmx.c:341)
==137415==    by 0x4A1A6A: dvipdfmx_main (dpx-dvipdfmx.c:516)
==137415==  Uninitialised value was created by a stack allocation
==137415==    at 0x4C6240: pdf_ximage_set_form (dpx-pdfximage.c:488)
==137415== 
==137415== Conditional jump or move depends on uninitialised value(s)
==137415==    at 0x5C3D31: max4 (dpx-dpxutil.c:63)
==137415==    by 0x4C640C: pdf_ximage_set_form (dpx-pdfximage.c:509)
==137415==    by 0x5CB639: pdf_include_page (dpx-epdf.c:497)
==137415==    by 0x4C5C2D: load_image (dpx-pdfximage.c:282)
==137415==    by 0x4C5EDE: pdf_ximage_findresource (dpx-pdfximage.c:368)
==137415==    by 0x5DE5E8: spc_handler_pdfm_image (dpx-spc_pdfm.c:998)
==137415==    by 0x4CFAF6: spc_exec_special (dpx-specials.c:579)
==137415==    by 0x5C6772: dvi_do_special (dpx-dvi.c:751)
==137415==    by 0x5C85A4: do_xxx (dpx-dvi.c:1443)
==137415==    by 0x5C959A: dvi_do_page (dpx-dvi.c:1869)
==137415==    by 0x4A13BA: do_dvi_pages (dpx-dvipdfmx.c:341)
==137415==    by 0x4A1A6A: dvipdfmx_main (dpx-dvipdfmx.c:516)
==137415==  Uninitialised value was created by a stack allocation
==137415==    at 0x4C6240: pdf_ximage_set_form (dpx-pdfximage.c:488)
==137415== 
==137415== Conditional jump or move depends on uninitialised value(s)
==137415==    at 0x5C3D47: max4 (dpx-dpxutil.c:64)
==137415==    by 0x4C640C: pdf_ximage_set_form (dpx-pdfximage.c:509)
==137415==    by 0x5CB639: pdf_include_page (dpx-epdf.c:497)
==137415==    by 0x4C5C2D: load_image (dpx-pdfximage.c:282)
==137415==    by 0x4C5EDE: pdf_ximage_findresource (dpx-pdfximage.c:368)
==137415==    by 0x5DE5E8: spc_handler_pdfm_image (dpx-spc_pdfm.c:998)
==137415==    by 0x4CFAF6: spc_exec_special (dpx-specials.c:579)
==137415==    by 0x5C6772: dvi_do_special (dpx-dvi.c:751)
==137415==    by 0x5C85A4: do_xxx (dpx-dvi.c:1443)
==137415==    by 0x5C959A: dvi_do_page (dpx-dvi.c:1869)
==137415==    by 0x4A13BA: do_dvi_pages (dpx-dvipdfmx.c:341)
==137415==    by 0x4A1A6A: dvipdfmx_main (dpx-dvipdfmx.c:516)
==137415==  Uninitialised value was created by a stack allocation
==137415==    at 0x4C6240: pdf_ximage_set_form (dpx-pdfximage.c:488)
==137415== 
==137415== Conditional jump or move depends on uninitialised value(s)
==137415==    at 0x4C6B52: scale_to_fit_F (dpx-pdfximage.c:717)
==137415==    by 0x4C6F26: pdf_ximage_scale_image (dpx-pdfximage.c:812)
==137415==    by 0x4A8ED9: pdf_dev_put_image (dpx-pdfdev.c:1806)
==137415==    by 0x5DE677: spc_handler_pdfm_image (dpx-spc_pdfm.c:1008)
==137415==    by 0x4CFAF6: spc_exec_special (dpx-specials.c:579)
==137415==    by 0x5C6772: dvi_do_special (dpx-dvi.c:751)
==137415==    by 0x5C85A4: do_xxx (dpx-dvi.c:1443)
==137415==    by 0x5C959A: dvi_do_page (dpx-dvi.c:1869)
==137415==    by 0x4A13BA: do_dvi_pages (dpx-dvipdfmx.c:341)
==137415==    by 0x4A1A6A: dvipdfmx_main (dpx-dvipdfmx.c:516)
==137415==    by 0x49FF73: dvipdfmx_simple_main (core-bridge.c:84)
==137415==    by 0x48480F: tectonic::engines::xdvipdfmx::XdvipdfmxEngine::process (xdvipdfmx.rs:64)
==137415==  Uninitialised value was created by a stack allocation
==137415==    at 0x4C6240: pdf_ximage_set_form (dpx-pdfximage.c:488)
==137415== 
==137415== Conditional jump or move depends on uninitialised value(s)
==137415==    at 0x4C6B5D: scale_to_fit_F (dpx-pdfximage.c:717)
==137415==    by 0x4C6F26: pdf_ximage_scale_image (dpx-pdfximage.c:812)
==137415==    by 0x4A8ED9: pdf_dev_put_image (dpx-pdfdev.c:1806)
==137415==    by 0x5DE677: spc_handler_pdfm_image (dpx-spc_pdfm.c:1008)
==137415==    by 0x4CFAF6: spc_exec_special (dpx-specials.c:579)
==137415==    by 0x5C6772: dvi_do_special (dpx-dvi.c:751)
==137415==    by 0x5C85A4: do_xxx (dpx-dvi.c:1443)
==137415==    by 0x5C959A: dvi_do_page (dpx-dvi.c:1869)
==137415==    by 0x4A13BA: do_dvi_pages (dpx-dvipdfmx.c:341)
==137415==    by 0x4A1A6A: dvipdfmx_main (dpx-dvipdfmx.c:516)
==137415==    by 0x49FF73: dvipdfmx_simple_main (core-bridge.c:84)
==137415==    by 0x48480F: tectonic::engines::xdvipdfmx::XdvipdfmxEngine::process (xdvipdfmx.rs:64)
==137415==  Uninitialised value was created by a stack allocation
==137415==    at 0x4C6240: pdf_ximage_set_form (dpx-pdfximage.c:488)
==137415== 
Writing /tmp/repro/pf_paper.pdf (1198198 bytes)
Skipped writing 2 intermediate files (use --keep-intermediates to keep them)
==137415== 
==137415== HEAP SUMMARY:
==137415==     in use at exit: 1,888,457 bytes in 9,093 blocks
==137415==   total heap usage: 1,457,008 allocs, 1,447,915 frees, 1,051,653,962 bytes allocated
==137415== 
==137415== LEAK SUMMARY:
==137415==    definitely lost: 157,692 bytes in 1,310 blocks
==137415==    indirectly lost: 309,212 bytes in 1,398 blocks
==137415==      possibly lost: 0 bytes in 0 blocks
==137415==    still reachable: 1,421,553 bytes in 6,385 blocks
==137415==         suppressed: 0 bytes in 0 blocks
==137415== Rerun with --leak-check=full to see details of leaked memory
==137415== 
==137415== For lists of detected and suppressed errors, rerun with: -s
==137415== ERROR SUMMARY: 162376 errors from 19 contexts (suppressed: 0 from 0)
```

</details>

<details><summary>valgrind tectonic @ oxidize</summary>

```console
$ ~/_/tectonic-oxidize on oxidize ⨯ valgrind --track-origins=yes target/debug/tectonic /tmp/repro/pf_paper.tex
==138124== Memcheck, a memory error detector
==138124== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==138124== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==138124== Command: target/debug/tectonic /tmp/repro/pf_paper.tex
==138124== 
note: this is a BETA release; ask questions and report bugs at https://tectonic.newton.cx/
Running TeX ...
==138124== Conditional jump or move depends on uninitialised value(s)
==138124==    at 0x147228D: try_fold<core::slice::Iter<u8>,usize,closure-0,core::result::Result<usize, usize>> (iterator.rs:1694)
==138124==    by 0x147228D: position<u8,closure-1> (mod.rs:3192)
==138124==    by 0x147228D: core::slice::memchr::memchr (memchr.rs:80)
==138124==    by 0x1472519: <i8 as core::slice::SliceContains>::slice_contains (mod.rs:5522)
==138124==    by 0xBB6417: core::slice::<impl [T]>::contains (mod.rs:1286)
==138124==    by 0xA1AFD2: tectonic_dvipdfmx::dpx_pdfparse::is_space (dpx_pdfparse.rs:46)
==138124==    by 0xA1B8CF: <&[u8] as tectonic_dvipdfmx::dpx_pdfparse::SkipWhite>::skip_white (dpx_pdfparse.rs:142)
==138124==    by 0xA1D45B: <&[u8] as tectonic_dvipdfmx::dpx_pdfparse::ParsePdfObj>::parse_pdf_object (dpx_pdfparse.rs:400)
==138124==    by 0xA1D00A: parse_pdf_object (dpx_pdfparse.rs:361)
==138124==    by 0x981499: tectonic_dvipdfmx::dpx_pdfobj::pdf_get_object (dpx_pdfobj.rs:3393)
==138124==    by 0x981A3F: pdf_deref_obj (dpx_pdfobj.rs:3441)
==138124==    by 0x986F2A: pdf_open (dpx_pdfobj.rs:4030)
==138124==    by 0x8B17EC: tectonic_engine::xetex_pic::pdf_get_rect (xetex_pic.rs:119)
==138124==    by 0x8B203B: tectonic_engine::xetex_pic::find_pic_file (xetex_pic.rs:249)
==138124==  Uninitialised value was created by a heap allocation
==138124==    at 0x48386AF: malloc (vg_replace_malloc.c:308)
==138124==    by 0x483ADE7: realloc (vg_replace_malloc.c:836)
==138124==    by 0xA4B8B7: renew (dpx_mem.rs:45)
==138124==    by 0x9774F4: pdf_add_stream (dpx_pdfobj.rs:2208)
==138124==    by 0x977B78: pdf_add_stream_flate (dpx_pdfobj.rs:2263)
==138124==    by 0x97C3EE: pdf_concat_stream (dpx_pdfobj.rs:2739)
==138124==    by 0x97C9B4: tectonic_dvipdfmx::dpx_pdfobj::pdf_stream_uncompress (dpx_pdfobj.rs:2769)
==138124==    by 0x97FE05: tectonic_dvipdfmx::dpx_pdfobj::read_objstm (dpx_pdfobj.rs:3241)
==138124==    by 0x9810BE: tectonic_dvipdfmx::dpx_pdfobj::pdf_get_object (dpx_pdfobj.rs:3365)
==138124==    by 0x981A3F: pdf_deref_obj (dpx_pdfobj.rs:3441)
==138124==    by 0x986F2A: pdf_open (dpx_pdfobj.rs:4030)
==138124==    by 0x8B17EC: tectonic_engine::xetex_pic::pdf_get_rect (xetex_pic.rs:119)
==138124== 
==138124== Conditional jump or move depends on uninitialised value(s)
==138124==    at 0xA1B8E9: <&[u8] as tectonic_dvipdfmx::dpx_pdfparse::SkipWhite>::skip_white (dpx_pdfparse.rs:142)
==138124==    by 0xA1D45B: <&[u8] as tectonic_dvipdfmx::dpx_pdfparse::ParsePdfObj>::parse_pdf_object (dpx_pdfparse.rs:400)
==138124==    by 0xA1D00A: parse_pdf_object (dpx_pdfparse.rs:361)
==138124==    by 0x981499: tectonic_dvipdfmx::dpx_pdfobj::pdf_get_object (dpx_pdfobj.rs:3393)
==138124==    by 0x981A3F: pdf_deref_obj (dpx_pdfobj.rs:3441)
==138124==    by 0x986F2A: pdf_open (dpx_pdfobj.rs:4030)
==138124==    by 0x8B17EC: tectonic_engine::xetex_pic::pdf_get_rect (xetex_pic.rs:119)
==138124==    by 0x8B203B: tectonic_engine::xetex_pic::find_pic_file (xetex_pic.rs:249)
==138124==    by 0x8B286E: load_picture (xetex_pic.rs:379)
==138124==    by 0x85C8A3: do_extension (xetex_xetex0.rs:24778)
==138124==    by 0x868CC7: main_control (xetex_xetex0.rs:26358)
==138124==    by 0x6A3747: tt_run_engine (xetex_ini.rs:10016)
==138124==  Uninitialised value was created by a heap allocation
==138124==    at 0x48386AF: malloc (vg_replace_malloc.c:308)
==138124==    by 0x483ADE7: realloc (vg_replace_malloc.c:836)
==138124==    by 0xA4B8B7: renew (dpx_mem.rs:45)
==138124==    by 0x9774F4: pdf_add_stream (dpx_pdfobj.rs:2208)
==138124==    by 0x977B78: pdf_add_stream_flate (dpx_pdfobj.rs:2263)
==138124==    by 0x97C3EE: pdf_concat_stream (dpx_pdfobj.rs:2739)
==138124==    by 0x97C9B4: tectonic_dvipdfmx::dpx_pdfobj::pdf_stream_uncompress (dpx_pdfobj.rs:2769)
==138124==    by 0x97FE05: tectonic_dvipdfmx::dpx_pdfobj::read_objstm (dpx_pdfobj.rs:3241)
==138124==    by 0x9810BE: tectonic_dvipdfmx::dpx_pdfobj::pdf_get_object (dpx_pdfobj.rs:3365)
==138124==    by 0x981A3F: pdf_deref_obj (dpx_pdfobj.rs:3441)
==138124==    by 0x986F2A: pdf_open (dpx_pdfobj.rs:4030)
==138124==    by 0x8B17EC: tectonic_engine::xetex_pic::pdf_get_rect (xetex_pic.rs:119)
==138124== 
==138124== Conditional jump or move depends on uninitialised value(s)
==138124==    at 0x483EEC5: bcmp (vg_replace_strmem.c:1113)
==138124==    by 0xBC3DAE: <[A] as core::slice::SlicePartialEq<A>>::equal (mod.rs:5381)
==138124==    by 0xBC3C91: core::slice::<impl core::cmp::PartialEq<[B]> for [A]>::eq (mod.rs:5303)
==138124==    by 0xBC39AB: core::cmp::impls::<impl core::cmp::PartialEq<&B> for &A>::eq (cmp.rs:1160)
==138124==    by 0x9BE82C: core::slice::<impl [T]>::starts_with (mod.rs:1314)
==138124==    by 0xA1D4AD: <&[u8] as tectonic_dvipdfmx::dpx_pdfparse::ParsePdfObj>::parse_pdf_object (dpx_pdfparse.rs:403)
==138124==    by 0xA1D00A: parse_pdf_object (dpx_pdfparse.rs:361)
==138124==    by 0x981499: tectonic_dvipdfmx::dpx_pdfobj::pdf_get_object (dpx_pdfobj.rs:3393)
==138124==    by 0x981A3F: pdf_deref_obj (dpx_pdfobj.rs:3441)
==138124==    by 0x986F2A: pdf_open (dpx_pdfobj.rs:4030)
==138124==    by 0x8B17EC: tectonic_engine::xetex_pic::pdf_get_rect (xetex_pic.rs:119)
==138124==    by 0x8B203B: tectonic_engine::xetex_pic::find_pic_file (xetex_pic.rs:249)
==138124==  Uninitialised value was created by a heap allocation
==138124==    at 0x48386AF: malloc (vg_replace_malloc.c:308)
==138124==    by 0x483ADE7: realloc (vg_replace_malloc.c:836)
==138124==    by 0xA4B8B7: renew (dpx_mem.rs:45)
==138124==    by 0x9774F4: pdf_add_stream (dpx_pdfobj.rs:2208)
==138124==    by 0x977B78: pdf_add_stream_flate (dpx_pdfobj.rs:2263)
==138124==    by 0x97C3EE: pdf_concat_stream (dpx_pdfobj.rs:2739)
==138124==    by 0x97C9B4: tectonic_dvipdfmx::dpx_pdfobj::pdf_stream_uncompress (dpx_pdfobj.rs:2769)
==138124==    by 0x97FE05: tectonic_dvipdfmx::dpx_pdfobj::read_objstm (dpx_pdfobj.rs:3241)
==138124==    by 0x9810BE: tectonic_dvipdfmx::dpx_pdfobj::pdf_get_object (dpx_pdfobj.rs:3365)
==138124==    by 0x981A3F: pdf_deref_obj (dpx_pdfobj.rs:3441)
==138124==    by 0x986F2A: pdf_open (dpx_pdfobj.rs:4030)
==138124==    by 0x8B17EC: tectonic_engine::xetex_pic::pdf_get_rect (xetex_pic.rs:119)
==138124== 
==138124== Conditional jump or move depends on uninitialised value(s)
==138124==    at 0x9BE837: core::slice::<impl [T]>::starts_with (mod.rs:1314)
==138124==    by 0xA1D4AD: <&[u8] as tectonic_dvipdfmx::dpx_pdfparse::ParsePdfObj>::parse_pdf_object (dpx_pdfparse.rs:403)
==138124==    by 0xA1D00A: parse_pdf_object (dpx_pdfparse.rs:361)
==138124==    by 0x981499: tectonic_dvipdfmx::dpx_pdfobj::pdf_get_object (dpx_pdfobj.rs:3393)
==138124==    by 0x981A3F: pdf_deref_obj (dpx_pdfobj.rs:3441)
==138124==    by 0x986F2A: pdf_open (dpx_pdfobj.rs:4030)
==138124==    by 0x8B17EC: tectonic_engine::xetex_pic::pdf_get_rect (xetex_pic.rs:119)
==138124==    by 0x8B203B: tectonic_engine::xetex_pic::find_pic_file (xetex_pic.rs:249)
==138124==    by 0x8B286E: load_picture (xetex_pic.rs:379)
==138124==    by 0x85C8A3: do_extension (xetex_xetex0.rs:24778)
==138124==    by 0x868CC7: main_control (xetex_xetex0.rs:26358)
==138124==    by 0x6A3747: tt_run_engine (xetex_ini.rs:10016)
==138124==  Uninitialised value was created by a heap allocation
==138124==    at 0x48386AF: malloc (vg_replace_malloc.c:308)
==138124==    by 0x483ADE7: realloc (vg_replace_malloc.c:836)
==138124==    by 0xA4B8B7: renew (dpx_mem.rs:45)
==138124==    by 0x9774F4: pdf_add_stream (dpx_pdfobj.rs:2208)
==138124==    by 0x977B78: pdf_add_stream_flate (dpx_pdfobj.rs:2263)
==138124==    by 0x97C3EE: pdf_concat_stream (dpx_pdfobj.rs:2739)
==138124==    by 0x97C9B4: tectonic_dvipdfmx::dpx_pdfobj::pdf_stream_uncompress (dpx_pdfobj.rs:2769)
==138124==    by 0x97FE05: tectonic_dvipdfmx::dpx_pdfobj::read_objstm (dpx_pdfobj.rs:3241)
==138124==    by 0x9810BE: tectonic_dvipdfmx::dpx_pdfobj::pdf_get_object (dpx_pdfobj.rs:3365)
==138124==    by 0x981A3F: pdf_deref_obj (dpx_pdfobj.rs:3441)
==138124==    by 0x986F2A: pdf_open (dpx_pdfobj.rs:4030)
==138124==    by 0x8B17EC: tectonic_engine::xetex_pic::pdf_get_rect (xetex_pic.rs:119)
==138124== 
==138124== Conditional jump or move depends on uninitialised value(s)
==138124==    at 0xA1B921: <&[u8] as tectonic_dvipdfmx::dpx_pdfparse::SkipWhite>::skip_white (dpx_pdfparse.rs:143)
==138124==    by 0xA1D45B: <&[u8] as tectonic_dvipdfmx::dpx_pdfparse::ParsePdfObj>::parse_pdf_object (dpx_pdfparse.rs:400)
==138124==    by 0xA1D00A: parse_pdf_object (dpx_pdfparse.rs:361)
==138124==    by 0x981499: tectonic_dvipdfmx::dpx_pdfobj::pdf_get_object (dpx_pdfobj.rs:3393)
==138124==    by 0x981A3F: pdf_deref_obj (dpx_pdfobj.rs:3441)
==138124==    by 0x986F2A: pdf_open (dpx_pdfobj.rs:4030)
==138124==    by 0x8B17EC: tectonic_engine::xetex_pic::pdf_get_rect (xetex_pic.rs:119)
==138124==    by 0x8B203B: tectonic_engine::xetex_pic::find_pic_file (xetex_pic.rs:249)
==138124==    by 0x8B286E: load_picture (xetex_pic.rs:379)
==138124==    by 0x85C8A3: do_extension (xetex_xetex0.rs:24778)
==138124==    by 0x868CC7: main_control (xetex_xetex0.rs:26358)
==138124==    by 0x6A3747: tt_run_engine (xetex_ini.rs:10016)
==138124==  Uninitialised value was created by a heap allocation
==138124==    at 0x48386AF: malloc (vg_replace_malloc.c:308)
==138124==    by 0x483ADE7: realloc (vg_replace_malloc.c:836)
==138124==    by 0xA4B8B7: renew (dpx_mem.rs:45)
==138124==    by 0x9774F4: pdf_add_stream (dpx_pdfobj.rs:2208)
==138124==    by 0x977B78: pdf_add_stream_flate (dpx_pdfobj.rs:2263)
==138124==    by 0x97C3EE: pdf_concat_stream (dpx_pdfobj.rs:2739)
==138124==    by 0x97C9B4: tectonic_dvipdfmx::dpx_pdfobj::pdf_stream_uncompress (dpx_pdfobj.rs:2769)
==138124==    by 0x97FE05: tectonic_dvipdfmx::dpx_pdfobj::read_objstm (dpx_pdfobj.rs:3241)
==138124==    by 0x9810BE: tectonic_dvipdfmx::dpx_pdfobj::pdf_get_object (dpx_pdfobj.rs:3365)
==138124==    by 0x981A3F: pdf_deref_obj (dpx_pdfobj.rs:3441)
==138124==    by 0x986F2A: pdf_open (dpx_pdfobj.rs:4030)
==138124==    by 0x8B17EC: tectonic_engine::xetex_pic::pdf_get_rect (xetex_pic.rs:119)
==138124== 
note: warnings were issued by the TeX engine; use --print and/or --keep-logs for details.
Running BibTeX ...
warning: errors were issued by BibTeX, but were ignored; use --print and/or --keep-logs for details.
Rerunning TeX because bibtex was run ...
Rerunning TeX because "pf_paper.aux" changed ...
Running xdvipdfmx ...
Writing /tmp/repro/pf_paper.pdf (1198197 bytes)
Skipped writing 2 intermediate files (use --keep-intermediates to keep them)
==138124== 
==138124== HEAP SUMMARY:
==138124==     in use at exit: 2,055,384 bytes in 18,575 blocks
==138124==   total heap usage: 1,492,000 allocs, 1,473,425 frees, 1,059,052,018 bytes allocated
==138124== 
==138124== LEAK SUMMARY:
==138124==    definitely lost: 254,788 bytes in 4,443 blocks
==138124==    indirectly lost: 358,724 bytes in 7,662 blocks
==138124==      possibly lost: 304 bytes in 1 blocks
==138124==    still reachable: 1,441,568 bytes in 6,469 blocks
==138124==         suppressed: 0 bytes in 0 blocks
==138124== Rerun with --leak-check=full to see details of leaked memory
==138124== 
==138124== For lists of detected and suppressed errors, rerun with: -s
==138124== ERROR SUMMARY: 232794 errors from 5 contexts (suppressed: 0 from 0)
```

</details>

The uninitialized reads seem to sometimes cause this output/error: https://github.com/crlf0710/tectonic/pull/168#issuecomment-546985858

### PR DESCRIPTION
**Pull request by Mrmaxmeier**
This takes a stab at #170.
The diff is pretty hacky still but I'd like to see the impact on the tests.

It seems like the problem was that the old code trusted an offset read from the PDF file: https://github.com/crlf0710/tectonic/blob/d385115bf40a0524d9c902af8f91c082be8d4c6f/dpx/src/dpx_pdfobj.rs#L3386-L3391

This fixes #170

### CODE REVIEW

**Comment by cormacrelf** [comment]
Lol, neither of our solutions worked. I am guessing both will be deterministic now. Keep yours though, Vec is more of an improvement.

**Comment by cormacrelf** [comment]
Hold up, does 'changes' sometimes mean for the better? If a test case was failing on oxidize, it appears as 'fixed'? If so, then they both worked?

**Comment by Mrmaxmeier** [comment]
> Hold up, does 'changes' sometimes mean for the better? If a test case was failing on oxidize, it appears as 'fixed'? If so, then they both worked?

Yup. This is a change from failed build (statuscode 1) to a successful build (statuscode 0).

valgrind doesn't complain anymore and this result should now be deterministic :tada:
```console
$ valgrind target/release/tectonic /tmp/repro/pf_paper.tex
==195562== Memcheck, a memory error detector
==195562== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==195562== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==195562== Command: target/release/tectonic /tmp/repro/pf_paper.tex
==195562== 
note: this is a BETA release; ask questions and report bugs at https://tectonic.newton.cx/
Running TeX ...
note: warnings were issued by the TeX engine; use --print and/or --keep-logs for details.
Running BibTeX ...
warning: errors were issued by BibTeX, but were ignored; use --print and/or --keep-logs for details.
Rerunning TeX because bibtex was run ...
Rerunning TeX because "pf_paper.aux" changed ...
Running xdvipdfmx ...
Writing /tmp/repro/pf_paper.pdf (1198196 bytes)
Skipped writing 2 intermediate files (use --keep-intermediates to keep them)
==195562== 
==195562== HEAP SUMMARY:
==195562==     in use at exit: 4,880,425 bytes in 19,059 blocks
==195562==   total heap usage: 1,492,276 allocs, 1,473,217 frees, 1,057,231,197 bytes allocated
==195562== 
==195562== LEAK SUMMARY:
==195562==    definitely lost: 2,974,634 bytes in 4,893 blocks
==195562==    indirectly lost: 368,190 bytes in 7,660 blocks
==195562==      possibly lost: 9,707 bytes in 4 blocks
==195562==    still reachable: 1,527,894 bytes in 6,502 blocks
==195562==         suppressed: 0 bytes in 0 blocks
==195562== Rerun with --leak-check=full to see details of leaked memory
==195562== 
==195562== For lists of detected and suppressed errors, rerun with: -s
==195562== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

File: dpx/src/dpx_pdfobj.rs [hunk 1]
```diff
@@ -1493,9 +1491,8 @@ pub unsafe extern "C" fn pdf_new_stream(mut flags: i32) -> *mut pdf_obj {
      */
     (*data).dict = pdf_new_dict();
     (*data)._flags = flags;
-    (*data).stream = 0 as *mut u8;
-    (*data).stream_length = 0_u32;
-    (*data).max_length = 0_u32;
+    let uninit_stream = std::mem::replace(&mut (*data).stream, Vec::new());
+    std::mem::forget(uninit_stream); // TODO: this is ugly
```
Comment (cormacrelf) [inline dpx/src/dpx_pdfobj.rs]: You can just initialize it before moving it to the allocated memory.

```rust
let data = new(std::mem::size_of::<pdf_stream>() as u32) as *mut pdf_stream;
let new_stream = pdf_stream {
    dict: pdf_new_dict(),
    _flags: flags,
    stream: Vec::new(),
    ...
};
*data = new_stream;
```

Comment (Mrmaxmeier) [reply dpx/src/dpx_pdfobj.rs]: This would still drop the uninitialized `pdf_stream` struct during `*data = new_stream`.
It looks like `ptr::write` is made for this as it doesn't drop the previous content.

File: dpx/src/dpx_pdfobj.rs [hunk 2]
```diff
@@ -3347,69 +3334,57 @@ unsafe fn pdf_get_object(
...
-        match current_block {
-            13472856163611868459 => {}
-            _ => {
-                warn!("Could not read object from object stream.");
-                return pdf_new_null();
+                let pdfobj_start = first + *data.offset(2*index as isize+1);
+                let pdfobj_end = if index as i32 == n - 1 { length } else { first + *data.offset(2*index as isize+3) };
+
+                let mut pdfobj_slice = &objstm_slice[pdfobj_start as usize..pdfobj_end as usize];
+                result = pdfobj_slice.parse_pdf_object(pf);
```
Comment (cormacrelf) [inline dpx/src/dpx_pdfobj.rs:3374]: This ~~is~~ was the last usage of the wrapper function https://github.com/Mrmaxmeier/tectonic/blob/e6ee43c3f155692e5ee47a3a974e4169f7b47f6d/dpx/src/dpx_pdfparse.rs#L353-L368

You can delete it now

Comment (cormacrelf) [reply dpx/src/dpx_pdfobj.rs:3374]: Oh my bad, there are a couple more.

**Comment by cormacrelf** [comment]
LGTM

**Comment by burrbull** [comment]
`pdf_array` also should be replaced with `Vec<u8>`

**Comment by burrbull** [comment]
I've tried, but made something wrong:
https://github.com/burrbull/tectonic/commit/3fa2a91a9da1f9abba0f566a6ee33472b556c697
